[tools]
go = "1.25"
golangci-lint = "2.5"
python = "3.13"

[tasks]
tidy = "go mod tidy"
build = "go build -o out/ps ./cmd/pseudolang"
run = "rm -rf out"
test = "go test ./..."

check = """
go vet ./...
go fmt ./...
golangci-lint run
"""
